# Generated by Django 5.2.8 on 2025-11-08 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='localidad',
            field=models.CharField(default='No especificada', max_length=50),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='madre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hogares_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='No especificada', max_length=100),
        ),
    ]
