# Generated by Django 5.2.8 on 2025-12-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_nino_fecha_ingreso_alter_padre_ocupacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMatriculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_acudiente', models.EmailField(max_length=100)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('correccion', 'En Corrección')], default='pendiente', max_length=20)),
                ('nombres_nino', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos_nino', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_nino', models.BigIntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=3, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('otro_pais', models.CharField(blank=True, max_length=50, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_nino', models.FileField(blank=True, null=True, upload_to='solicitudes/ninos/fotos/')),
                ('carnet_vacunacion_nino', models.FileField(blank=True, null=True, upload_to='solicitudes/ninos/vacunacion/')),
                ('certificado_eps_nino', models.FileField(blank=True, null=True, upload_to='solicitudes/ninos/eps/')),
                ('registro_civil_nino', models.FileField(blank=True, null=True, upload_to='solicitudes/ninos/registro_civil/')),
                ('tipo_documento_padre', models.CharField(blank=True, max_length=5, null=True)),
                ('documento_padre', models.BigIntegerField(blank=True, null=True)),
                ('nombres_padre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos_padre', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_padre', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono_padre', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_padre', models.CharField(blank=True, max_length=200, null=True)),
                ('ocupacion_padre', models.CharField(blank=True, max_length=50, null=True)),
                ('otra_ocupacion_padre', models.CharField(blank=True, max_length=50, null=True)),
                ('estrato_padre', models.IntegerField(blank=True, null=True)),
                ('password_padre', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_identidad_padre', models.FileField(blank=True, null=True, upload_to='solicitudes/padres/cedulas/')),
                ('clasificacion_sisben_padre', models.FileField(blank=True, null=True, upload_to='solicitudes/padres/sisben/')),
                ('campos_corregir', models.JSONField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_matricula', to='core.hogarcomunitario')),
            ],
            options={
                'db_table': 'solicitudes_matriculacion',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
