# Generated by Django 5.2.8 on 2025-12-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_solicitudmatriculacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudmatriculacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='solicitudmatriculacion',
            old_name='fecha_respuesta',
            new_name='fecha_aprobacion',
        ),
        migrations.RenameField(
            model_name='solicitudmatriculacion',
            old_name='fecha_envio',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='solicitudmatriculacion',
            old_name='fecha_nacimiento',
            new_name='fecha_nacimiento_nino',
        ),
        migrations.RenameField(
            model_name='solicitudmatriculacion',
            old_name='genero',
            new_name='genero_nino',
        ),
        migrations.RenameField(
            model_name='solicitudmatriculacion',
            old_name='nacionalidad',
            new_name='nivel_educativo_padre',
        ),
        migrations.RemoveField(
            model_name='solicitudmatriculacion',
            name='estrato_padre',
        ),
        migrations.RemoveField(
            model_name='solicitudmatriculacion',
            name='otra_ocupacion_padre',
        ),
        migrations.RemoveField(
            model_name='solicitudmatriculacion',
            name='otro_pais',
        ),
        migrations.RemoveField(
            model_name='solicitudmatriculacion',
            name='tipo_sangre',
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='barrio_padre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='observaciones_nino',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='tipo_sangre_nino',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudmatriculacion',
            name='documento_nino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudmatriculacion',
            name='documento_padre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudmatriculacion',
            name='ocupacion_padre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudmatriculacion',
            name='parentesco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
