# Generated by Django 5.2.8 on 2025-12-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_solicitudmatriculacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='intentos_correccion',
            field=models.IntegerField(default=0),
        ),
    ]
