# Generated by Django 5.2.8 on 2025-12-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_solicitudmatriculacion_intentos_correccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='otra_discapacidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='tiene_discapacidad',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='tipos_discapacidad',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
