# Generated by Django 5.2.8 on 2025-12-04 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_solicitudmatriculacion_otra_discapacidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_modelo', models.CharField(choices=[('solicitud', 'Solicitud de Matriculación'), ('nino', 'Niño'), ('padre', 'Padre/Acudiente')], max_length=20)),
                ('objeto_id', models.PositiveIntegerField()),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('accion', models.CharField(default='modificacion', max_length=50)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_cambios',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['tipo_modelo', 'objeto_id'], name='historial_c_tipo_mo_8f003a_idx'), models.Index(fields=['fecha_cambio'], name='historial_c_fecha_c_de46fe_idx')],
            },
        ),
    ]
