# Generated by Django 5.2.8 on 2025-12-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_historialcambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('retirado', 'Retirado')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='nino',
            name='observaciones_medicas',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones médicas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel_educativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
