# Generated by Django 5.2.8 on 2025-12-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_nino_estado_nino_observaciones_medicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudmatriculacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('correccion', 'En Corrección'), ('cancelado_expiracion', 'Cancelado por Expiración'), ('cancelado_usuario', 'Cancelado por Usuario'), ('token_usado', 'Token Usado')], default='pendiente', max_length=30),
        ),
    ]
