# Generated by Django 5.2.8 on 2025-12-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_agregar_estados_cancelacion_y_campos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='F', max_length=1),
        ),
    ]
