# Generated by Django 5.2.8 on 2025-12-09 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_agregar_campo_sexo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LocalidadBogota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('numero', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Localidad de Bogotá',
                'verbose_name_plural': 'Localidades de Bogotá',
                'db_table': 'localidades_bogota',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='departamento_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padres_solicitantes', to='core.departamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes', to='core.departamento'),
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='localidad_bogota_padre',
            field=models.ForeignKey(blank=True, help_text='Solo si vive en Bogotá D.C.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padres_solicitantes', to='core.localidadbogota'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='localidad_bogota',
            field=models.ForeignKey(blank=True, help_text='Solo aplica si vive en Bogotá D.C.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes', to='core.localidadbogota'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('es_capital', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='core.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
                'ordering': ['departamento__nombre', 'nombre'],
                'unique_together': {('nombre', 'departamento')},
            },
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='ciudad_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padres_solicitantes', to='core.municipio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes', to='core.municipio'),
        ),
    ]
