# Generated by Django 5.2.8 on 2025-12-09 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_agregar_geografia_colombia'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogarcomunitario',
            name='localidad_bogota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hogares', to='core.localidadbogota'),
        ),
    ]
