# Generated by Django 5.2.8 on 2025-12-09 22:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_agregar_localidad_bogota_hogar'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogarcomunitario',
            name='fecha_habilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='estado',
            field=models.CharField(choices=[('pendiente_visita', 'Pendiente de Visita'), ('visita_agendada', 'Visita Agendada'), ('en_evaluacion', 'En Evaluación'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('rechazado', 'Rechazado'), ('en_mantenimiento', 'En Mantenimiento')], default='pendiente_visita', max_length=25),
        ),
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='agendada', max_length=20)),
                ('tipo_visita', models.CharField(choices=[('V1', 'Primera Visita - Habilitación'), ('V2', 'Visita de Seguimiento'), ('V3', 'Visita Extraordinaria')], default='V1', max_length=3)),
                ('observaciones_agenda', models.TextField(blank=True, help_text='Observaciones al agendar la visita', null=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('correo_enviado', models.BooleanField(default=False)),
                ('fecha_envio_correo', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_creadas', to=settings.AUTH_USER_MODEL)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_tecnicas', to='core.hogarcomunitario')),
                ('visitador', models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'administrador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita Técnica',
                'verbose_name_plural': 'Visitas Técnicas',
                'db_table': 'visitas_tecnicas',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='ActaVisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocalizacion_lat_verificada', models.DecimalField(decimal_places=7, help_text='Latitud capturada en el momento de la visita', max_digits=10)),
                ('geolocalizacion_lon_verificada', models.DecimalField(decimal_places=7, help_text='Longitud capturada en el momento de la visita', max_digits=10)),
                ('direccion_verificada', models.CharField(max_length=200)),
                ('direccion_coincide', models.BooleanField(default=False, help_text='¿La dirección verificada coincide con la reportada en el FUR?')),
                ('observaciones_direccion', models.TextField(blank=True, null=True)),
                ('estrato_verificado', models.IntegerField(help_text='Estrato confirmado del recibo de servicio público', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('estrato_coincide', models.BooleanField(default=False)),
                ('foto_recibo_servicio', models.ImageField(help_text='Foto del recibo de servicio público para verificar estrato', upload_to='visitas/recibos/')),
                ('tiene_agua_potable', models.BooleanField(default=False)),
                ('agua_continua', models.BooleanField(default=False, help_text='Suministro continuo')),
                ('agua_legal', models.BooleanField(default=False, help_text='Conexión legal')),
                ('tiene_energia', models.BooleanField(default=False)),
                ('energia_continua', models.BooleanField(default=False)),
                ('energia_legal', models.BooleanField(default=False)),
                ('tiene_alcantarillado', models.BooleanField(default=False)),
                ('manejo_excretas_adecuado', models.BooleanField(default=False, help_text='Si no hay alcantarillado, ¿hay manejo adecuado de excretas?')),
                ('estado_pisos', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('muy_malo', 'Muy Malo')], max_length=15)),
                ('estado_paredes', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('muy_malo', 'Muy Malo')], max_length=15)),
                ('estado_techos', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('muy_malo', 'Muy Malo')], max_length=15)),
                ('ventilacion_adecuada', models.BooleanField(default=False)),
                ('iluminacion_natural_adecuada', models.BooleanField(default=False)),
                ('observaciones_infraestructura', models.TextField(blank=True, null=True)),
                ('proximidad_rios', models.BooleanField(default=False)),
                ('proximidad_deslizamientos', models.BooleanField(default=False)),
                ('proximidad_trafico_intenso', models.BooleanField(default=False)),
                ('proximidad_contaminacion', models.BooleanField(default=False)),
                ('nivel_riesgo_general', models.CharField(choices=[('sin_riesgo', 'Sin Riesgo'), ('riesgo_bajo', 'Riesgo Bajo'), ('riesgo_medio', 'Riesgo Medio'), ('riesgo_alto', 'Riesgo Alto'), ('riesgo_critico', 'Riesgo Crítico')], default='sin_riesgo', max_length=20)),
                ('descripcion_riesgos', models.TextField(blank=True, help_text='Descripción detallada de los riesgos identificados', null=True)),
                ('area_social_largo', models.DecimalField(decimal_places=2, help_text='Largo del área social en metros', max_digits=5)),
                ('area_social_ancho', models.DecimalField(decimal_places=2, help_text='Ancho del área social en metros', max_digits=5)),
                ('area_social_total', models.DecimalField(blank=True, decimal_places=2, help_text='Área total calculada (largo x ancho)', max_digits=7, null=True)),
                ('foto_area_social_medidas', models.ImageField(help_text='Foto del área social mostrando las medidas', upload_to='visitas/areas_sociales/')),
                ('tiene_patio_cubierto', models.BooleanField(default=False)),
                ('patio_largo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('patio_ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('patio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('foto_patio_medidas', models.ImageField(blank=True, null=True, upload_to='visitas/patios/')),
                ('num_banos_verificado', models.IntegerField(help_text='Cantidad de baños/baterías sanitarias', validators=[django.core.validators.MinValueValidator(1)])),
                ('estado_higiene_banos', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('aceptable', 'Aceptable'), ('deficiente', 'Deficiente'), ('inaceptable', 'Inaceptable')], max_length=15)),
                ('foto_bano_1', models.ImageField(help_text='Foto del baño principal', upload_to='visitas/banos/')),
                ('foto_bano_2', models.ImageField(blank=True, help_text='Foto de baño adicional (si hay más de uno)', null=True, upload_to='visitas/banos/')),
                ('foto_fachada', models.ImageField(help_text='Foto de la fachada de la casa', upload_to='visitas/fachadas/')),
                ('foto_fachada_numeracion', models.ImageField(blank=True, help_text='Foto de la numeración de la casa', null=True, upload_to='visitas/fachadas/')),
                ('capacidad_calculada', models.IntegerField(blank=True, help_text='Capacidad calculada según el área disponible (1.5m² por niño)', null=True)),
                ('capacidad_recomendada', models.IntegerField(help_text='Capacidad recomendada por el visitador')),
                ('justificacion_capacidad', models.TextField(blank=True, help_text='Justificación de la capacidad recomendada', null=True)),
                ('resultado_visita', models.CharField(choices=[('aprobado', 'Aprobado'), ('aprobado_condiciones', 'Aprobado con Condiciones'), ('rechazado', 'Rechazado'), ('requiere_segunda_visita', 'Requiere Segunda Visita')], max_length=30)),
                ('observaciones_generales', models.TextField(help_text='Observaciones y conclusiones de la visita')),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('condiciones_aprobacion', models.TextField(blank=True, help_text='Condiciones que debe cumplir si es aprobado con condiciones', null=True)),
                ('firma_visitador', models.ImageField(blank=True, help_text='Firma digital del visitador', null=True, upload_to='visitas/firmas/')),
                ('firma_madre', models.ImageField(blank=True, help_text='Firma de la madre comunitaria', null=True, upload_to='visitas/firmas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('completado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_completadas', to=settings.AUTH_USER_MODEL)),
                ('visita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='core.visitatecnica')),
            ],
            options={
                'verbose_name': 'Acta de Visita Técnica',
                'verbose_name_plural': 'Actas de Visitas Técnicas',
                'db_table': 'actas_visitas_tecnicas',
            },
        ),
    ]
