# Generated by Django 5.2.8 on 2025-12-10 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_sistema_visitas_tecnicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='convivientehogar',
            name='antecedentes_pdf',
            field=models.FileField(blank=True, null=True, upload_to='hogares/antecedentes_convivientes/'),
        ),
        migrations.AddField(
            model_name='convivientehogar',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convivientehogar',
            name='nombre_completo',
            field=models.CharField(default='NOMBRE_PENDIENTE', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convivientehogar',
            name='numero_documento',
            field=models.CharField(default='DOCUMENTO_PENDIENTE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convivientehogar',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil')], default='CC', max_length=2),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='area_social_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metros cuadrados del área social disponible para los niños', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='capacidad_calculada',
            field=models.IntegerField(blank=True, help_text='Capacidad calculada según área social (m²/2)', null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='fecha_primera_visita',
            field=models.DateField(blank=True, help_text='Fecha programada para la primera visita técnica', null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='formulario_completo',
            field=models.BooleanField(default=False, help_text='Indica si se completó el formulario 2 de visita técnica'),
        ),
        migrations.AlterField(
            model_name='convivientehogar',
            name='cedula',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convivientehogar',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convivientehogar',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='capacidad_maxima',
            field=models.IntegerField(default=15, help_text='Capacidad máxima aprobada después de visita técnica'),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='estado',
            field=models.CharField(choices=[('pendiente_revision', 'Pendiente de Revisión'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_mantenimiento', 'En Mantenimiento'), ('pendiente_visita', 'Pendiente de Visita'), ('visita_agendada', 'Visita Agendada'), ('en_evaluacion', 'En Evaluación'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='pendiente_revision', max_length=30),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='material_construccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
