# Generated by Django 5.2.8 on 2025-12-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_convivientehogar_antecedentes_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogarcomunitario',
            name='confirmacion_casa_propia',
            field=models.BooleanField(default=False, help_text='Confirmo que presto mi casa para el cuidado de los niños'),
        ),
    ]
