# Generated by Django 5.2.8 on 2025-12-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_hogarcomunitario_confirmacion_casa_propia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hogarcomunitario',
            name='confirmacion_casa_propia',
        ),
        migrations.AddField(
            model_name='madrecomunitaria',
            name='certificado_laboral',
            field=models.FileField(blank=True, null=True, upload_to='madres_documentos/certificados_laborales/'),
        ),
    ]
