# Generated by Django 5.2.8 on 2025-12-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_hogarcomunitario_confirmacion_casa_propia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madrecomunitaria',
            name='disponibilidad_tiempo',
        ),
        migrations.AddField(
            model_name='madrecomunitaria',
            name='carta_disponibilidad',
            field=models.FileField(blank=True, null=True, upload_to='madres_documentos/disponibilidad/'),
        ),
    ]
