# Generated by Django 5.2.8 on 2025-12-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_madrecomunitaria_disponibilidad_tiempo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='localidad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
