# Generated by Django 5.2.8 on 2025-12-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_hogarcomunitario_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogarcomunitario',
            name='estado_aptitud',
            field=models.CharField(choices=[('no_apto', 'No Apto'), ('apto', 'Apto')], default='no_apto', help_text="Estado de aptitud del hogar. Se actualiza a 'Apto' después de la primera visita aprobada", max_length=20),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='observaciones_visita',
            field=models.TextField(blank=True, help_text='Observaciones de la última visita técnica realizada'),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='proxima_visita',
            field=models.DateField(blank=True, help_text='Fecha programada para la próxima visita técnica (calculada automáticamente)', null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='ultima_visita',
            field=models.DateField(blank=True, help_text='Fecha de la última visita técnica realizada', null=True),
        ),
    ]
