# Generated by Django 5.2.8 on 2025-12-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_hogarcomunitario_estado_aptitud_and_more'),
    ]

    operations = [
    ]
