# Generated by Django 5.2.8 on 2025-12-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20251210_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogarcomunitario',
            name='capacidad',
            field=models.IntegerField(blank=True, help_text='Capacidad aprobada del hogar (entre 12 y 15 niños según normativa ICBF)', null=True),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='capacidad_maxima',
            field=models.IntegerField(default=15, help_text='Capacidad máxima permitida (15 niños según normativa)'),
        ),
    ]
