# Generated by Django 5.2.8 on 2025-12-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_agregar_campo_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='tipo_documento',
            field=models.CharField(choices=[('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('CV', 'Carné de Vacunación'), ('AN', 'Acta de Nacimiento'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], default='RC', max_length=2, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='documento',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número de Documento'),
        ),
    ]
