# Generated by Django 5.2.8 on 2025-12-11 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_nino_tipo_documento_alter_nino_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='cupos_validados',
            field=models.BooleanField(default=False, help_text='Indica si se validaron los cupos disponibles'),
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='padre_solicitante',
            field=models.ForeignKey(blank=True, help_text='Padre que inició la solicitud (solo para tipo_solicitud=solicitud_padre)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_matricula', to='core.padre'),
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='tiene_cupos_disponibles',
            field=models.BooleanField(default=False, help_text='Resultado de la validación de cupos'),
        ),
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='tipo_solicitud',
            field=models.CharField(choices=[('invitacion_madre', 'Invitación de Madre Comunitaria'), ('solicitud_padre', 'Solicitud Iniciada por Padre/Tutor')], default='invitacion_madre', help_text='Tipo de flujo: invitación de madre o solicitud de padre', max_length=30),
        ),
    ]
