# Generated by Django 5.2.8 on 2025-12-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_solicitudmatriculacion_cupos_validados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madrecomunitaria',
            name='nivel_escolaridad',
            field=models.CharField(choices=[('Bachiller', 'Bachiller'), ('Técnico', 'Técnico'), ('Tecnólogo', 'Tecnólogo'), ('Profesional', 'Profesional')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
    ]
