# Generated by Django 5.2.8 on 2025-12-13 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_madrecomunitaria_nivel_escolaridad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRetiroMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('cambio_hogar', 'Cambio de hogar comunitario'), ('cambio_ciudad', 'Cambio de ciudad/departamento'), ('economico', 'Razones económicas'), ('personal', 'Razones personales/familiares'), ('salud', 'Problemas de salud'), ('cambio_colegio', 'Cambio de colegio'), ('traslado_laboral', 'Traslado laboral'), ('otro', 'Otro motivo')], help_text='Motivo del retiro', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del motivo (máximo 500 caracteres)', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado_padre', 'Cancelado por el Padre')], default='pendiente', help_text='Estado actual de la solicitud', max_length=30)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se creó la solicitud')),
                ('fecha_respuesta', models.DateTimeField(blank=True, help_text='Fecha en que la madre respondió', null=True)),
                ('observaciones_madre', models.TextField(blank=True, help_text='Observaciones o motivo del rechazo (si aplica)', null=True)),
                ('hogar', models.ForeignKey(help_text='El hogar del que se retira el niño', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_retiro', to='core.hogarcomunitario')),
                ('nino', models.ForeignKey(help_text='El niño que se desea retirar', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_retiro', to='core.nino')),
                ('padre', models.ForeignKey(help_text='El padre que solicita el retiro', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_retiro', to='core.padre')),
                ('respondida_por', models.ForeignKey(blank=True, help_text='La madre que procesó la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiros_procesados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Retiro de Matrícula',
                'verbose_name_plural': 'Solicitudes de Retiro de Matrícula',
                'db_table': 'solicitudes_retiro_matricula',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['nino', 'estado'], name='solicitudes_nino_id_1f70ef_idx'), models.Index(fields=['padre', 'fecha_solicitud'], name='solicitudes_padre_i_dfd2d8_idx'), models.Index(fields=['hogar', 'estado'], name='solicitudes_hogar_i_0f1ce6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('nino', 'estado'), name='una_solicitud_pendiente_por_nino')],
            },
        ),
    ]
