# Generated by Django 5.2.8 on 2025-12-13 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_simplify_hogar_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrioBogota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrios', to='core.localidadbogota')),
            ],
            options={
                'verbose_name': 'Barrio de Bogotá',
                'verbose_name_plural': 'Barrios de Bogotá',
                'db_table': 'barrios_bogota',
                'ordering': ['localidad', 'nombre'],
                'unique_together': {('localidad', 'nombre')},
            },
        ),
    ]
