# Generated by Django 5.2.8 on 2025-12-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_barriobogota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que fue eliminado', null=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Marca si el niño ha sido eliminado lógicamente del sistema'),
        ),
    ]
