# Generated by Django 5.2.8 on 2025-12-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_nino_deleted_at_nino_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmatriculacion',
            name='tipo_documento_nino',
            field=models.CharField(blank=True, help_text='Tipo de documento del niño (Tarjeta de Identidad, Cédula, Pasaporte, etc.)', max_length=30, null=True),
        ),
    ]
