# Generated by Django 5.2.8 on 2025-12-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_solicitudmatriculacion_tipo_documento_nino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmatriculacion',
            name='tipo_documento_nino',
            field=models.CharField(blank=True, choices=[('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('CV', 'Carné de Vacunación'), ('AN', 'Acta de Nacimiento'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], help_text='Tipo de documento del niño', max_length=2, null=True),
        ),
    ]
