# Generated by Django 5.2.8 on 2025-11-11 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_delete_novedad_usuario_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('clase', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('causa', models.CharField(blank=True, max_length=255)),
                ('disposicion', models.TextField(blank=True)),
                ('acuerdos', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nino')),
            ],
        ),
    ]
