# Generated by Django 5.2.8 on 2025-11-13 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_remove_usuario_username_hogarcomunitario_barrio_and_more'),
        ('novedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('clase', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('causa', models.CharField(blank=True, max_length=255)),
                ('disposicion', models.TextField(blank=True)),
                ('acuerdos', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('a', 'Cambios en los estados de salud'), ('b', 'Cambios en el estado emocional'), ('c', 'Razones de inasistencia y llegadas tarde'), ('d', 'Inapetencia'), ('e', 'Cambios de medicamentos'), ('f', 'Inasistencia de medicamentos'), ('g', 'Sin registro civil'), ('h', 'Sin afiliación en salud'), ('i', 'Sin esquema de vacunación'), ('j', 'Otra')], max_length=1, verbose_name='Tipo de novedad')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
