# Generated by Django 5.2.8 on 2025-11-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='tipo',
            field=models.CharField(choices=[('a', 'Cambios en los estados de salud'), ('b', 'Cambios en el estado emocional'), ('c', 'Razones de inasistencia y llegadas tarde'), ('d', 'Inapetencia'), ('e', 'Cambios de medicamentos'), ('f', 'Inasistencia de medicamentos'), ('g', 'Sin registro civil'), ('h', 'Sin afiliación en salud'), ('i', 'Sin esquema de vacunación'), ('j', 'Otra')], default='a', max_length=1, verbose_name='Tipo de novedad'),
            preserve_default=False,
        ),
    ]
