# Generated by Django 5.2.8 on 2025-11-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_initial'),
        ('novedades', '0002_novedad_tipo'),
    ]

    operations = [
    ]
