# Generated by Django 5.2.8 on 2025-11-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0003_merge_0002_initial_0002_novedad_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='usuario',
        ),
        migrations.AddField(
            model_name='novedad',
            name='docente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
