# Generated by Django 5.2.8 on 2025-12-05 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0004_novedad_planeacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='planeacion',
        ),
    ]
