# Generated by Django 5.2.8 on 2025-12-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0009_alter_seguimientodiario_observacion_relevante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollonino',
            name='alertas_mes',
            field=models.TextField(default='', help_text='Alertas automáticas sobre inasistencias, valoraciones bajas o novedades.', verbose_name='Alertas del Mes'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='aspectos_a_mejorar',
            field=models.TextField(default='', help_text='Lista generada automáticamente de áreas de oportunidad.', verbose_name='Aspectos por Mejorar'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='conclusion_general',
            field=models.TextField(default='', help_text='Resumen automático del progreso y estado general del niño en el mes.', verbose_name='Conclusión General del Desarrollo'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='evaluacion_autonomia',
            field=models.TextField(default='', verbose_name='Evaluación Autonomía'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='evaluacion_cognitiva',
            field=models.TextField(default='', verbose_name='Evaluación Cognitiva'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='evaluacion_comunicativa',
            field=models.TextField(default='', verbose_name='Evaluación Comunicativa / Lenguaje'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='evaluacion_corporal',
            field=models.TextField(default='', verbose_name='Evaluación Corporal / Motricidad'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='evaluacion_socio_afectiva',
            field=models.TextField(default='', verbose_name='Evaluación Socio-afectiva'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='fortalezas_mes',
            field=models.TextField(default='', help_text='Lista generada automáticamente de aspectos positivos.', verbose_name='Fortalezas del Mes'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='observaciones_adicionales',
            field=models.TextField(blank=True, default='', help_text='Espacio para notas o comentarios manuales del educador.', verbose_name='Observaciones Adicionales del Educador'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='recomendaciones_personales',
            field=models.TextField(blank=True, default='', help_text='Recomendaciones específicas para la familia o el seguimiento.', verbose_name='Recomendaciones Personales'),
        ),
    ]
